# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20e0c15e4ee6fc5d7835e8ae6bd5a15d48b07aef417bf0c5eec8428b16006af34dfdc8534a4597edcf5b35cca266142ad9555e1f0b64e3dff55350f0176341ea

test:
  secret_key_base: 774f9bc6596a658af224e1d5f31b100cabcee6d35d75cd51789310b4c758955879d3d5497ec387a80f0c9752947efca5aa5b13bc7cc3ff83684d2521facfe2ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
